name: Build SMF plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      MAJOR_VERSION:
        description: "Version string for wireshark tag needed to build can be v#.#.# or v#.#.#-rc#"
        required: false
        default: ''
      MINOR_VERSION:
        description: "Minor version of the wireshark tag"
        required: false
        default: ''
      PATCH_VERSION:
        description: "Patch version of the wireshark tag"
        required: false
        default: ''
jobs:
  # Commenting out intel mac for regular builds as it is currently broken.
  #build_macos:
  #  uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/macos.yml@main
  #  with:
  #    MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
  #    MINOR_VERSION: ${{ inputs.MINOR_VERSION || '0' }}
  #    PATCH_VERSION: ${{ inputs.PATCH_VERSION || '5' }}
  build_macos_arm64:
    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/macos_arm64.yml
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '4' }}
      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '0' }}
  build_windows:
    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/windows.yml
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '4' }}
      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '0' }}
  build_linux:
    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/ubuntu.yml
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '4' }}
      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '0' }}
