name: Create Release
on:
  push:
    branches: release-automation
  workflow_dispatch:
    inputs:
      MAJOR_VERSION:
        description: "Version string for wireshark tag needed to build can be v#.#.# or v#.#.#-rc#"
        required: true
        default: "4"
      MINOR_VERSION:
        description: "Minor version of the wireshark tag"
        required: true
        default: "0"
      PATCH_VERSION:
          description: "Patch version of the wireshark tag"
          required: true
          default: "5"
      RELEASE_PATCH_VERSION:
        description: "PATCH for SMF plugin"
        required: true
        default: ""
env:
  LINUX_x86_64_PLUGIN_NAME: wireshark-smf-linux-x86_64.tar.gz
  WINDOWS_x64_PLUGIN_NAME: wireshark-smf-windows-x64.zip
  MACOS_ARM64_PLUGIN_NAME: wireshark-smf-macos-arm64.tar.gz

jobs:
  build_linux:
    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/ubuntu.yml@release-automation
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '0' }}
      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '5' }}
  
  build_windows:
    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/windows.yml@release-automation
    with:
      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '0' }}
      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '5' }}
    
#  build_macos:
#    uses: NeelPatel-Solace/wireshark-smf-plugin/.github/workflows/macos.yml@release-automation
#    with:
#      MAJOR_VERSION: ${{ inputs.MAJOR_VERSION || '4' }}
#      MINOR_VERSION: ${{ inputs.MINOR_VERSION || '0' }}
#      PATCH_VERSION: ${{ inputs.PATCH_VERSION || '5' }}
      
  create_release:
    runs-on: ubuntu-22.04
    #needs: [build_linux, build_windows, build_macos]
    needs: [build_linux, build_windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
            path: ${{ github.workspace }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
            name: "Wireshark SMF Plugin ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.RELEASE_PATCH_VERSION }}"
            tag: "${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.RELEASE_PATCH_VERSION }}"
            #artifacts: "${{ env.LINUX_x86_64_PLUGIN_NAME }}/*, ${{ env.WINDOWS_x64_PLUGIN_NAME }}/*, ${{ env.MACOS_ARM64_PLUGIN_NAME }}/*"
            artifacts: "${{ env.LINUX_x86_64_PLUGIN_NAME }}/*, ${{ env.WINDOWS_x64_PLUGIN_NAME }}/*"
            bodyFile: "${{ github.workspace }}/docs/wireshark_smf_4-0-x_instructions.md"
            draft: true